### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by tadeokondrak** [blamario/canadian-income-tax#1]
This tool looks really useful!

Unfortunately, I can't get it to build using `cabal build`:

```
Build profile: -w ghc-9.6.4 -O1
In order, the following will be built (use -v for more details):
 - canadian-income-tax-2022.2.1 (lib) (first run)
 - canadian-income-tax-2022.2.1 (exe:serve-canadian-taxes) (first run)
 - canadian-income-tax-2022.2.1 (exe:complete-canadian-taxes) (first run)
Preprocessing library for canadian-income-tax-2022.2.1..
Building library for canadian-income-tax-2022.2.1..
[ 9 of 52] Compiling Tax.Canada.T1.FieldNames.QC ( src/Tax/Canada/T1/FieldNames/QC.hs, /home/tdeo/repos/github.com/blamario/canadian-income-tax/dist-newstyle/build/x86_64-linux/ghc-9.6.4/canadian-income-tax-2022.2.1/build/Tax/Canada/T1/FieldNames/QC.o, /home/tdeo/repos/github.com/blamario/canadian-income-tax/dist-newstyle/build/x86_64-linux/ghc-9.6.4/canadian-income-tax-2022.2.1/build/Tax/Canada/T1/FieldNames/QC.dyn_o )

src/Tax/Canada/T1/FieldNames/QC.hs:51:12: error:
    Ambiguous occurrence ‘threshold’
    It could refer to
       either the field ‘threshold’ of record ‘TaxIncomeBracket’,
              imported from ‘Tax.Canada.Shared’ at src/Tax/Canada/T1/FieldNames/QC.hs:15:27-47
           or the field ‘threshold’ of record ‘MedicalExpenses’,
              imported from ‘Tax.Canada.T1.Types’ at src/Tax/Canada/T1/FieldNames/QC.hs:16:1-26
   |
51 |            threshold = partA1.column4.threshold}
   |            ^^^^^^^^^

src/Tax/Canada/T1/FieldNames/QC.hs:83:4: error:
    Ambiguous occurrence ‘threshold’
    It could refer to
       either the field ‘threshold’ of record ‘TaxIncomeBracket’,
              imported from ‘Tax.Canada.Shared’ at src/Tax/Canada/T1/FieldNames/QC.hs:15:27-47
           or the field ‘threshold’ of record ‘MedicalExpenses’,
              imported from ‘Tax.Canada.T1.Types’ at src/Tax/Canada/T1/FieldNames/QC.hs:16:1-26
   |
83 |    threshold = Field ["Line113", "Amount"] Amount,
   |    ^^^^^^^^^

src/Tax/Canada/T1/FieldNames/QC.hs:106:4: error:
    Ambiguous occurrence ‘step6_RefundOrBalanceOwing’
    It could refer to
       either the field ‘step6_RefundOrBalanceOwing’ of record ‘Page8’,
              imported from ‘Tax.Canada.T1.Types’ at src/Tax/Canada/T1/FieldNames/QC.hs:16:1-26
           or the field ‘step6_RefundOrBalanceOwing’ of record ‘Page7’,
              imported from ‘Tax.Canada.T1.Types’ at src/Tax/Canada/T1/FieldNames/QC.hs:16:1-26
    |
106 |    step6_RefundOrBalanceOwing = within "Step6-Continued" Rank2.<$> page8step6Fields,
    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build canadian-income-tax-2022.2.1 (which is required
by exe:serve-canadian-taxes from canadian-income-tax-2022.2.1 and
exe:complete-canadian-taxes from canadian-income-tax-2022.2.1).
```

I did get `cabal install canadian-income-tax` to work, but I'm worried that that version isn't up-to-date to use 2023 forms. Let me know if that isn't the case. Thanks!

**Comment by blamario** [comment]
It's been recently updated for the 2023 forms. I'm going to release the 2023 version on Hackage soon.

As for the build errors, I'll have a look but if you're in a hurry it builds with GHC 9.8.1. You'll also need `cabal.project` with flags

```
allow-newer: data-functor-logistic:base
```

**Comment by blamario** [comment]
Fixed by https://github.com/blamario/canadian-income-tax/commit/47d44b59605df1f4502677ce27e875d6dd549487
